import Header from '@/component/Header/Header'
import Footer from '@/component/Layout/Footer'
import { MainProviders } from '@/provider/MainProvider'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<MainProviders>
					<Header />
					{children}
					<Footer />
				</MainProviders>
			</body>
		</html>
	)
}
